services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    image: infra-api
    ports:
      - "8001:8000"

  frontend:
    build:
      context: ../frontend
    image: infra-frontend
    depends_on:
      - api
    ports:
      - "8080:80"
