version: "3.9"

services:
  api:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8001:8000"   # expose backend on 8001 (matches your App.tsx)

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "5173:80"     # serve built frontend on http://localhost:5173
    depends_on:
      - api
